### ISSUE TITLE
Extension breaks highlighting within some cases in php

### ISSUE THREAD

**Issue by Jackky90** [pcbowers/alpine-intellisense#10]
Here what I have with extension ON:
![image](https://user-images.githubusercontent.com/49349165/197319883-20aca6e3-2761-46ec-b3a5-c08213001e84.png)

And when extension is OFF, highlighting works normally:
![image](https://user-images.githubusercontent.com/49349165/197319931-1e19438f-f43e-4f1b-89cc-90a1988c5fa2.png)

**Comment by pcbowers** [comment]
@Jackky90 Thanks for putting in an issue! Closing this in favor of #5. I don't currently have a solution, but am open to PR's that would change the syntax to support better syntax highlighting!
